### ISSUE TITLE
JBCroppableView Monotouch

### ISSUE THREAD

**Issue by mapo80** [jberlana/JBCroppableView#4]
Hi,

I've converted your script to Monotouch. It' available online on github at https://github.com/mapo80/JBCroppableView-Monotouch

Thanks for your code! :+1:

**Comment by jberlana** [comment]
wow! good work dude, and thanks for the mention!

Kind regards!

**Comment by mapo80** [comment]
Thanks you for your code!! ;)

**Comment by fukemy** [comment]
Hi. Can you convert it to swift?
